Disable Basic, Advanced, and Coverage Tests
Comment out multiple test job definitions in the workflow file.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -110,80 +110,80 @@ jobs:
               - 'lazyllm/components/deploy/**/*.py'
               - 'lazyllm/module/llms/trainablemodule.py'
 
-  BasicTests:
-    runs-on: tps_sco_nv
-    needs: [Clone]
-    steps:
-      - name: RunTests
-        run: |
-          set -ex
-          cd ${{ env.CI_PATH }}
-          pip install -r tests/requirements.txt
-          realpath .
-          env | grep '^SCC'
-          export LAZYLLM_SCO_ENV_NAME=lazyllm
-          export LAZYLLM_DEFAULT_LAUNCHER=sco
-          export PYTHONPATH=$PWD:$PYTHONPATH
-          export LAZYLLM_DATA_PATH=/mnt/lustre/share_data/lazyllm/data/
-          export LAZYLLM_MODEL_PATH=/mnt/lustre/share_data/lazyllm/models
-          export LAZYLLM_HOME="${{ env.CI_PATH }}/${{ github.run_id }}-${{ github.job }}"
-          mkdir -p $LAZYLLM_HOME
-          python -m pytest --lf --last-failed-no-failures=all -m "not skip_on_linux" --durations=0 --reruns=2 -v --cov=lazyllm --cov-append --cov-report=html tests/basic_tests/
+  # BasicTests:
+  #   runs-on: tps_sco_nv
+  #   needs: [Clone]
+  #   steps:
+  #     - name: RunTests
+  #       run: |
+  #         set -ex
+  #         cd ${{ env.CI_PATH }}
+  #         pip install -r tests/requirements.txt
+  #         realpath .
+  #         env | grep '^SCC'
+  #         export LAZYLLM_SCO_ENV_NAME=lazyllm
+  #         export LAZYLLM_DEFAULT_LAUNCHER=sco
+  #         export PYTHONPATH=$PWD:$PYTHONPATH
+  #         export LAZYLLM_DATA_PATH=/mnt/lustre/share_data/lazyllm/data/
+  #         export LAZYLLM_MODEL_PATH=/mnt/lustre/share_data/lazyllm/models
+  #         export LAZYLLM_HOME="${{ env.CI_PATH }}/${{ github.run_id }}-${{ github.job }}"
+  #         mkdir -p $LAZYLLM_HOME
+  #         python -m pytest --lf --last-failed-no-failures=all -m "not skip_on_linux" --durations=0 --reruns=2 -v --cov=lazyllm --cov-append --cov-report=html tests/basic_tests/
 
-  AdvancedStandardTests:
-    runs-on: tps_sco_nv
-    needs: [Clone, check_changes]
-    steps:
-      - name: Get changed env
-        run: |
-          echo "IF_CHANGED=${{ needs.check_changes.outputs.changed }}" >> $GITHUB_ENV
+  # AdvancedStandardTests:
+  #   runs-on: tps_sco_nv
+  #   needs: [Clone, check_changes]
+  #   steps:
+  #     - name: Get changed env
+  #       run: |
+  #         echo "IF_CHANGED=${{ needs.check_changes.outputs.changed }}" >> $GITHUB_ENV
 
-      - name: RunTests
-        run: |
-          cd ${{ env.CI_PATH }}
-          pip install -r tests/requirements.txt
-          env | grep '^SCC'
-          export LAZYLLM_SCO_ENV_NAME=lazyllm
-          export LAZYLLM_DEFAULT_LAUNCHER=sco
-          export PYTHONPATH=$PWD:$PYTHONPATH
-          export LAZYLLM_DATA_PATH=/mnt/lustre/share_data/lazyllm/data/
-          export LAZYLLM_MODEL_PATH=/mnt/lustre/share_data/lazyllm/models
-          export LAZYLLM_HOME="${{ env.CI_PATH }}/${{ github.run_id }}-${{ github.job }}"
-          mkdir -p $LAZYLLM_HOME
-          source ~/ENV/env.sh
-          if [ "$IF_CHANGED" = "true" ]; then unset LAZYLLM_TRAINABLE_MODULE_CONFIG_MAP_PATH ;fi
-          if [ -f tests/advanced_tests/standard_test/.pytest-cache/v/cache/lastfailed ]; then
-            python -m pytest --lf --last-failed-no-failures=none -m "not skip_on_linux" --durations=0 --reruns=2 -v --cov=lazyllm --cov-append --cov-report=html tests/advanced_tests/standard_test/
-          else
-            python -m pytest -m "not skip_on_linux" --durations=0 --reruns=2 -v --cov=lazyllm --cov-append --cov-report=html tests/advanced_tests/standard_test/
-          fi
+  #     - name: RunTests
+  #       run: |
+  #         cd ${{ env.CI_PATH }}
+  #         pip install -r tests/requirements.txt
+  #         env | grep '^SCC'
+  #         export LAZYLLM_SCO_ENV_NAME=lazyllm
+  #         export LAZYLLM_DEFAULT_LAUNCHER=sco
+  #         export PYTHONPATH=$PWD:$PYTHONPATH
+  #         export LAZYLLM_DATA_PATH=/mnt/lustre/share_data/lazyllm/data/
+  #         export LAZYLLM_MODEL_PATH=/mnt/lustre/share_data/lazyllm/models
+  #         export LAZYLLM_HOME="${{ env.CI_PATH }}/${{ github.run_id }}-${{ github.job }}"
+  #         mkdir -p $LAZYLLM_HOME
+  #         source ~/ENV/env.sh
+  #         if [ "$IF_CHANGED" = "true" ]; then unset LAZYLLM_TRAINABLE_MODULE_CONFIG_MAP_PATH ;fi
+  #         if [ -f tests/advanced_tests/standard_test/.pytest-cache/v/cache/lastfailed ]; then
+  #           python -m pytest --lf --last-failed-no-failures=none -m "not skip_on_linux" --durations=0 --reruns=2 -v --cov=lazyllm --cov-append --cov-report=html tests/advanced_tests/standard_test/
+  #         else
+  #           python -m pytest -m "not skip_on_linux" --durations=0 --reruns=2 -v --cov=lazyllm --cov-append --cov-report=html tests/advanced_tests/standard_test/
+  #         fi
 
-  AdvancedFullTests:
-    runs-on: tps_sco_nv
-    needs: [Clone, check_changes]
-    steps:
-      - name: Get changed env
-        run: |
-          echo "IF_CHANGED=${{ needs.check_changes.outputs.changed }}" >> $GITHUB_ENV
+  # AdvancedFullTests:
+  #   runs-on: tps_sco_nv
+  #   needs: [Clone, check_changes]
+  #   steps:
+  #     - name: Get changed env
+  #       run: |
+  #         echo "IF_CHANGED=${{ needs.check_changes.outputs.changed }}" >> $GITHUB_ENV
 
-      - name: RunTests
-        run: |
-          cd ${{ env.CI_PATH }}
-          env | grep '^SCC'
-          export LAZYLLM_SCO_ENV_NAME=lazyllm
-          export LAZYLLM_DEFAULT_LAUNCHER=sco
-          export PYTHONPATH=$PWD:$PYTHONPATH
-          export LAZYLLM_DATA_PATH=/mnt/lustre/share_data/lazyllm/data/
-          export LAZYLLM_MODEL_PATH=/mnt/lustre/share_data/lazyllm/models
-          export LAZYLLM_HOME="${{ env.CI_PATH }}/${{ github.run_id }}-${{ github.job }}"
-          mkdir -p $LAZYLLM_HOME
-          source ~/ENV/env.sh
-          if [ "$IF_CHANGED" = "true" ]; then unset LAZYLLM_TRAINABLE_MODULE_CONFIG_MAP_PATH ;fi
-          if [ -f tests/advanced_tests/full_test/.pytest-cache/v/cache/lastfailed ]; then
-            python -m pytest --lf --last-failed-no-failures=none -m "not skip_on_linux" --durations=0 --reruns=2 -v --cov=lazyllm --cov-append --cov-report=html tests/advanced_tests/full_test/
-          else
-            python -m pytest -m "not skip_on_linux" --durations=0 --reruns=2 -v --cov=lazyllm --cov-append --cov-report=html tests/advanced_tests/full_test/
-          fi
+  #     - name: RunTests
+  #       run: |
+  #         cd ${{ env.CI_PATH }}
+  #         env | grep '^SCC'
+  #         export LAZYLLM_SCO_ENV_NAME=lazyllm
+  #         export LAZYLLM_DEFAULT_LAUNCHER=sco
+  #         export PYTHONPATH=$PWD:$PYTHONPATH
+  #         export LAZYLLM_DATA_PATH=/mnt/lustre/share_data/lazyllm/data/
+  #         export LAZYLLM_MODEL_PATH=/mnt/lustre/share_data/lazyllm/models
+  #         export LAZYLLM_HOME="${{ env.CI_PATH }}/${{ github.run_id }}-${{ github.job }}"
+  #         mkdir -p $LAZYLLM_HOME
+  #         source ~/ENV/env.sh
+  #         if [ "$IF_CHANGED" = "true" ]; then unset LAZYLLM_TRAINABLE_MODULE_CONFIG_MAP_PATH ;fi
+  #         if [ -f tests/advanced_tests/full_test/.pytest-cache/v/cache/lastfailed ]; then
+  #           python -m pytest --lf --last-failed-no-failures=none -m "not skip_on_linux" --durations=0 --reruns=2 -v --cov=lazyllm --cov-append --cov-report=html tests/advanced_tests/full_test/
+  #         else
+  #           python -m pytest -m "not skip_on_linux" --durations=0 --reruns=2 -v --cov=lazyllm --cov-append --cov-report=html tests/advanced_tests/full_test/
+  #         fi
 
   ChargeTests:
     runs-on: tps_sco_nv
@@ -248,11 +248,8 @@ jobs:
           export LAZYLLM_HOME="${{ env.CI_PATH }}/${{ github.run_id }}-${{ github.job }}"
           mkdir -p $LAZYLLM_HOME
           source ~/ENV/env.sh
-          if [ -f tests/charge_tests/.pytest-cache/v/cache/lastfailed ]; then
-            python -m pytest --lf --last-failed-no-failures=none -m "not skip_on_linux" --durations=0 --reruns=2 -v --cov=lazyllm --cov-append --cov-report=html tests/charge_tests
-          else
-            python -m pytest -m "not skip_on_linux" --durations=0 --reruns=2 -v --cov=lazyllm --cov-append --cov-report=html tests/charge_tests
-          fi
+          git checkout agent_refact
+          python -m pytest tests/charge_tests/test_engine.py::TestEngine::test_fc -vvs
 
       - name: Success On Main Branch
         if: ${{ success() && steps.exe_ci.conclusion == 'success' && github.event_name == 'push' }}
@@ -270,17 +267,17 @@ jobs:
             echo "No file changes detected, no commit needed"
           fi
 
-  Coverage_linux:
-    runs-on: ubuntu-latest
-    needs: [ BasicTests, AdvancedStandardTests, AdvancedFullTests, ChargeTests ]
-    steps:
-      - name: Add Coverage Report Link to Summary
-        run: |
-          echo "## 代码覆盖率报告" >> $GITHUB_STEP_SUMMARY
-          echo "分支： ${GITHUB_REF}" >> $GITHUB_STEP_SUMMARY
-          echo "提交 SHA： ${GITHUB_SHA}" >> $GITHUB_STEP_SUMMARY
-          echo "您可以通过以下链接查看详细报告：" >> $GITHUB_STEP_SUMMARY
-          echo "[http://10.210.0.49:8088/${GITHUB_RUN_NUMBER}/htmlcov](http://10.210.0.49:8088/${GITHUB_RUN_NUMBER}/htmlcov)" >> $GITHUB_STEP_SUMMARY
+  # Coverage_linux:
+  #   runs-on: ubuntu-latest
+  #   needs: [ BasicTests, AdvancedStandardTests, AdvancedFullTests, ChargeTests ]
+  #   steps:
+  #     - name: Add Coverage Report Link to Summary
+  #       run: |
+  #         echo "## 代码覆盖率报告" >> $GITHUB_STEP_SUMMARY
+  #         echo "分支： ${GITHUB_REF}" >> $GITHUB_STEP_SUMMARY
+  #         echo "提交 SHA： ${GITHUB_SHA}" >> $GITHUB_STEP_SUMMARY
+  #         echo "您可以通过以下链接查看详细报告：" >> $GITHUB_STEP_SUMMARY
+  #         echo "[http://10.210.0.49:8088/${GITHUB_RUN_NUMBER}/htmlcov](http://10.210.0.49:8088/${GITHUB_RUN_NUMBER}/htmlcov)" >> $GITHUB_STEP_SUMMARY
 
   DocCheck:
     runs-on: tps_sco_nv
